version: '3.8'

services:
  app:
    container_name: app
    build: ./
    ports:
      - 8080:8080
    privileged: true
    volumes:
      - ./:/app:cached
    tty: true
    stdin_open: true
    command: /app/bin/init.sh